# -*- coding: utf-8 -*-
"""NN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CPchX8I_6biVluOvQtBqTQQU2WYWCDd4
"""

import seaborn as sns
import numpy as np

from google.colab import drive
drive.mount('/content/drive')
INPUT_FILE = "/content/drive/MyDrive/210/Neural Network/Input/DE1_0_2008_to_2010_Outpatient_Claims_Sample_1_labeled.csv"

import os

print(os.listdir("/content/drive/MyDrive/210/Neural Network"))

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder, StandardScaler
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    roc_curve,
    precision_recall_curve,
    average_precision_score,
    ConfusionMatrixDisplay
)

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping


# ==================================================
# 1. LOAD DATA
# ==================================================

#INPUT_FILE = "DE1_0_2008_to_2010_Outpatient_Claims_Sample_1_labeled.csv"

df = pd.read_csv(INPUT_FILE, low_memory=False)

print("Rows loaded:", len(df))


# ==================================================
# 2. DROP PAYMENT SIGNALS
# ==================================================

DROP_COLS = [
    "DESYNPUF_ID", "CLM_ID",

    # Payment amounts
    "CLM_PMT_AMT",
    "NCH_PRMRY_PYR_CLM_PD_AMT",
    "NCH_BENE_BLOOD_DDCTBL_LBLTY_AM",
    "NCH_BENE_PTB_DDCTBL_AMT",
    "NCH_BENE_PTB_COINSRNC_AMT",

    # Payment-derived signals
    "Zero_Amount_Signal",
    "Claim_Adjustment_Signal",

    # Engineered signals
    "High_HCPCS_Count_Signal",
    "High_Diagnosis_Count_Signal",
    "Weak_Primary_Diagnosis_Signal",
    "High_Intensity_Weak_Dx_Signal",
    "Any_High_Intensity_HCPCS_Signal",
    "Missing_Primary_Diagnosis_Signal",
    "Missing_Provider_Number_Signal",
]

df_model = df.drop(columns=DROP_COLS, errors="ignore").copy()


# ==================================================
# 3. DATE FEATURES
# ==================================================

if "CLM_FROM_DT" in df_model.columns:
    df_model["CLM_FROM_DT"] = pd.to_datetime(
        df_model["CLM_FROM_DT"].astype(str),
        format="%Y%m%d",
        errors="coerce"
    )
    df_model["claim_month"] = df_model["CLM_FROM_DT"].dt.month
    df_model["claim_year"] = df_model["CLM_FROM_DT"].dt.year
    df_model.drop(columns=["CLM_FROM_DT"], inplace=True)

if "CLM_THRU_DT" in df_model.columns:
    df_model.drop(columns=["CLM_THRU_DT"], inplace=True)


# ==================================================
# 4. TARGET
# ==================================================

TARGET = "High_Risk"

X = df_model.drop(columns=[TARGET])
y = df_model[TARGET].astype(int)


# ==================================================
# 5. 60/20/20 SPLIT
# ==================================================

X_temp, X_test, y_temp, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

X_train, X_val, y_train, y_val = train_test_split(
    X_temp, y_temp,
    test_size=0.25,
    stratify=y_temp,
    random_state=42
)

print("Train:", len(X_train))
print("Validation:", len(X_val))
print("Test:", len(X_test))


# ==================================================
# 6. ENCODING (FIT ON TRAIN ONLY)
# ==================================================

categorical_cols = X_train.select_dtypes(include=["object"]).columns.tolist()

enc = None
if categorical_cols:
    enc = OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1)

    X_train[categorical_cols] = enc.fit_transform(
        X_train[categorical_cols].fillna("__NA__")
    )

    X_val[categorical_cols] = enc.transform(
        X_val[categorical_cols].fillna("__NA__")
    )

    X_test[categorical_cols] = enc.transform(
        X_test[categorical_cols].fillna("__NA__")
    )

for df_part in [X_train, X_val, X_test]:
    for col in df_part.columns:
        df_part[col] = pd.to_numeric(df_part[col], errors="coerce").fillna(-1)


# ==================================================
# 7. SCALE NUMERIC FEATURES
# ==================================================

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)


# ==================================================
# 8. BUILD NEURAL NETWORK
# ==================================================

model = Sequential([
    Dense(32, activation="relu", input_shape=(X_train_scaled.shape[1],)),
    Dropout(0.3),
    Dense(16, activation="relu"),
    Dense(1, activation="sigmoid")
])

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["AUC"]
)

early_stop = EarlyStopping(
    monitor="val_loss",
    patience=5,
    restore_best_weights=True
)

history = model.fit(
    X_train_scaled,
    y_train,
    validation_data=(X_val_scaled, y_val),
    epochs=50,
    batch_size=512,
    callbacks=[early_stop],
    verbose=1
)

print("Training complete.")


# ==================================================
# 9. TEST SET EVALUATION
# ==================================================

y_test_prob = model.predict(X_test_scaled).ravel()

# ---- Default Threshold (0.5) ----
#default_threshold = 0.5
default_threshold = 0.2
y_test_pred_default = (y_test_prob >= default_threshold).astype(int)

print("\n===== TEST PERFORMANCE (Threshold = 0.2) =====")
print("Accuracy :", accuracy_score(y_test, y_test_pred_default))
print("Precision:", precision_score(y_test, y_test_pred_default))
print("Recall   :", recall_score(y_test, y_test_pred_default))
print("F1 Score :", f1_score(y_test, y_test_pred_default))
print("ROC-AUC  :", roc_auc_score(y_test, y_test_prob))

# ==================================================
# 12. SAVE PLOTS
# ==================================================

OUTPUT_DIR = "/content/drive/MyDrive/210/Neural Network/Output"
os.makedirs(OUTPUT_DIR, exist_ok=True)
df_test_results = df.loc[y_test.index].copy()
df_test_results["High_Risk_actual"] = y_test
df_test_results["High_Risk_pred"] = y_test_pred_default
df_test_results["High_Risk_prob"] = y_test_prob

output_path = os.path.join(OUTPUT_DIR, "nn_test_set_predictions.csv")
df_test_results.to_csv(output_path, index=False)

print("Saved test predictions to:", output_path)

# Confusion Matrix
cm = confusion_matrix(y_test, y_test_pred_default)
cm_percent = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]

labels = np.array([
    [f"{cm[i,j]}\n({cm_percent[i,j]:.1%})" for j in range(cm.shape[1])]
    for i in range(cm.shape[0])
])

# Create custom soft color map
soft_colors = np.array([
    ["#d8f3dc", "#fde2e4"],   # TN (soft green), FP (soft red)
    ["#fde2e4", "#cdeac0"]    # FN (soft red), TP (soft green)
])

plt.figure(figsize=(6,5))

ax = sns.heatmap(
    cm,
    annot=labels,
    fmt="",
    cmap="Greys",
    cbar=False,
    xticklabels=["Low Risk (0)", "High Risk (1)"],
    yticklabels=["Low Risk (0)", "High Risk (1)"],
    linewidths=1,
    linecolor="gray"
)

# Apply soft background coloring
for i in range(2):
    for j in range(2):
        ax.add_patch(
            plt.Rectangle(
                (j, i), 1, 1,
                fill=True,
                color=soft_colors[i, j],
                alpha=0.8
            )
        )

plt.title("Confusion Matrix (Neural Network)")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.tight_layout()
plt.show()
plt.savefig(os.path.join(OUTPUT_DIR, "confusion matrix.png"), dpi=150)

# ROC Curve
fpr, tpr, _ = roc_curve(y_test, y_test_prob)
roc_auc = roc_auc_score(y_test, y_test_prob)

fig, ax = plt.subplots(figsize=(6,5))
ax.plot(fpr, tpr, lw=2, label=f"AUC = {roc_auc:.3f}")
ax.plot([0,1],[0,1],"--")
ax.set_xlabel("False Positive Rate")
ax.set_ylabel("True Positive Rate")
ax.set_title("ROC Curve (NN)")
ax.legend()
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "nn_roc_curve.png"), dpi=150)
plt.close()

# PR Curve
precision_vals, recall_vals, _ = precision_recall_curve(y_test, y_test_prob)
pr_auc = average_precision_score(y_test, y_test_prob)

fig, ax = plt.subplots(figsize=(6,5))
ax.plot(recall_vals, precision_vals, lw=2, label=f"PR-AUC = {pr_auc:.3f}")
ax.set_xlabel("Recall")
ax.set_ylabel("Precision")
ax.set_title("Precision-Recall Curve (NN)")
ax.legend()
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "nn_pr_curve.png"), dpi=150)
plt.close()

print("\nAll NN evaluation plots saved.")

# XGBoost

from xgboost import XGBClassifier
from xgboost.callback import EarlyStopping
import xgboost
print(xgboost.__version__)

model_XG = XGBClassifier(
    n_estimators=1000,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="binary:logistic",
    eval_metric="auc",
    tree_method="hist",
    random_state=42,
    early_stopping_rounds=50
)

model_XG.fit(
    X_train,
    y_train,
    eval_set=[(X_val, y_val)],
    verbose=True
)

print("XG Boost Training complete.")

#XG Boost best threshold & Evaluate

import numpy as np
from sklearn.metrics import precision_recall_curve

# Get probabilities
y_test_prob_XG = model_XG.predict_proba(X_test)[:, 1]

# Compute precision-recall curve
precision, recall, thresholds = precision_recall_curve(y_test, y_test_prob_XG)

# Compute F1 for every threshold
f1_scores = 2 * (precision * recall) / (precision + recall + 1e-10)

# Find best threshold
best_index_XG = np.argmax(f1_scores)
best_threshold_XG = thresholds[best_index_XG]

print("Best Threshold (Max F1) XG:", best_threshold_XG)
print("Best F1: XG", f1_scores[best_index_XG])
print("Precision at Best XG:", precision[best_index_XG])
print("Recall at Best XG:", recall[best_index_XG])

y_test_pred_opt_XG = (y_test_prob_XG >= best_threshold_XG).astype(int)

print("\n===== TEST PERFORMANCE (Optimal Threshold) =====")
print("Accuracy :", accuracy_score(y_test, y_test_pred_opt_XG))
print("Precision:", precision_score(y_test, y_test_pred_opt_XG))
print("Recall   :", recall_score(y_test, y_test_pred_opt_XG))
print("F1 Score :", f1_score(y_test, y_test_pred_opt_XG))
print("ROC-AUC  :", roc_auc_score(y_test, y_test_prob_XG))

# ==================================================
# XGBOOST v2 — FAST CPU TUNING VERSION
# ==================================================

from sklearn.model_selection import RandomizedSearchCV
from xgboost import XGBClassifier


negatives = (y_train == 0).sum()
positives = (y_train == 1).sum()

scale_pos_weight = negatives / positives

print("Negatives:", negatives)
print("Positives:", positives)
print("scale_pos_weight:", scale_pos_weight)

# 1️⃣ Subsample data for tuning
X_train_sample = X_train.sample(frac=0.35, random_state=42)
y_train_sample = y_train.loc[X_train_sample.index]

# 2️⃣ Smaller search space
param_dist_small = {
    "max_depth": [4, 5],
    "min_child_weight": [3, 5],
    "learning_rate": [0.05, 0.1],
    "gamma": [0, 0.1],
}

# 3️⃣ Lightweight base model
model_XG_v2_base = XGBClassifier(
    n_estimators=200,
    objective="binary:logistic",
    eval_metric="auc",
    tree_method="hist",
    random_state=42,
    scale_pos_weight=scale_pos_weight
)

random_search_v2 = RandomizedSearchCV(
    estimator=model_XG_v2_base,
    param_distributions=param_dist_small,
    n_iter=10,
    scoring="roc_auc",
    cv=2,
    verbose=2,
    random_state=42,
    n_jobs=1
)

random_search_v2.fit(X_train_sample, y_train_sample)

print("Best Params:", random_search_v2.best_params_)
print("Best CV AUC:", random_search_v2.best_score_)

model_XG_v3_final = XGBClassifier(
    n_estimators=1500,
    learning_rate=0.1,
    max_depth=5,
    min_child_weight=3,
    gamma=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="binary:logistic",
    eval_metric="auc",
    tree_method="hist",
    random_state=42,
    scale_pos_weight=scale_pos_weight,
    early_stopping_rounds=50
)

model_XG_v3_final.fit(
    X_train,
    y_train,
    eval_set=[(X_val, y_val)],
    verbose=True
)

# ==================================================
# Test Evaluation
# ==================================================

from sklearn.metrics import roc_auc_score, accuracy_score, precision_score, recall_score, f1_score

# Predict probabilities
y_test_prob_XG_v3 = model_XG_v3_final.predict_proba(X_test)[:, 1]

# Default 0.5 threshold
y_test_pred_XG_v3 = (y_test_prob_XG_v3 >= 0.44).astype(int)#0.3724803

print("\n===== TEST PERFORMANCE (Threshold = 0.5) =====")
print("Accuracy :", accuracy_score(y_test, y_test_pred_XG_v3))
print("Precision:", precision_score(y_test, y_test_pred_XG_v3))
print("Recall   :", recall_score(y_test, y_test_pred_XG_v3))
print("F1 Score :", f1_score(y_test, y_test_pred_XG_v3))
print("ROC-AUC  :", roc_auc_score(y_test, y_test_prob_XG_v3))

cm = confusion_matrix(y_test, y_test_pred_XG_v3)

print("\nConfusion Matrix (Counts):")
print(cm)

# Plot
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(values_format='d')
plt.title("Confusion Matrix (Threshold = 0.44)")
plt.show()

from sklearn.metrics import precision_recall_curve
import numpy as np

precision, recall, thresholds = precision_recall_curve(y_test, y_test_prob_XG_v3)

target_recall = 0.7

# Find all thresholds meeting recall requirement
indices = np.where(recall >= target_recall)[0]

if len(indices) > 0:
    idx = indices[-1]  # choose highest threshold that still meets recall
    threshold_recall = thresholds[idx]

    print("Threshold for Recall ≥ 0.7:", threshold_recall)
    print("Precision at that threshold:", precision[idx])
    print("Recall at that threshold:", recall[idx])
else:
    print("No threshold achieves recall ≥ 0.75")